### ISSUE TITLE
Implement Display for Table and Column

### ISSUE THREAD

**Issue by Razican** [diesel-rs/diesel-dynamic-schema#12]
Sometimes it's interesting to pass the reference to a `Table` or a `Column` around, and still have the string representation of the name, for example, to query about that table to a dynamic schema stored in the database itself.

Implementing `Display` for `Table` and `Column` should be straightforward if their inner type `T` implements `Display` too.

I can implement it if you find this useful :)

**Comment by weiznich** [comment]
See the reasoning in #13 for why this issue is closed.

> Implementing Display for those types is an bad idea in my opinion as this opens up for trying to build a query out of strings using this types. This would result then in incorrectly generated SQL as the Display implementation does not provide a correct string representation for those types that could be used in SQL. Fore example the implementation of the Column type only lists the column name and both implementations does not handle quoting those names in the right database depended way. As a conclusion I do not think that Display is the right trait to be implemented for those types. They are only exists as nodes for the diesel query builder. There is no need to print the directly in my opinion.
